// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectWebIV_Backend.Data;

namespace ProjectWebIV_Backend.Migrations
{
    [DbContext(typeof(PostContext))]
    [Migration("20190502121407_InitalMigration")]
    partial class InitalMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProjectWebIV_Backend.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("PostId");

                    b.Property<string>("Text")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.ToTable("Comment");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2019, 5, 2, 14, 14, 7, 330, DateTimeKind.Local).AddTicks(3372),
                            Name = "Robbie Verdurme",
                            PostId = 1,
                            Text = "Comment 1"
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2019, 5, 2, 14, 14, 7, 330, DateTimeKind.Local).AddTicks(4455),
                            Name = "Robbie Verdurme",
                            PostId = 1,
                            Text = "Comment 2"
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2019, 5, 2, 14, 14, 7, 330, DateTimeKind.Local).AddTicks(4473),
                            Name = "Robbie Verdurme",
                            PostId = 1,
                            Text = "Comment 3"
                        });
                });

            modelBuilder.Entity("ProjectWebIV_Backend.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("ProjectWebIV_Backend.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created");

                    b.Property<string>("Description");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2019, 5, 2, 14, 14, 7, 330, DateTimeKind.Local).AddTicks(860),
                            Description = "testje",
                            Title = "Post 1"
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2019, 5, 2, 14, 14, 7, 330, DateTimeKind.Local).AddTicks(1351),
                            Title = "Post 2"
                        });
                });

            modelBuilder.Entity("ProjectWebIV_Backend.Models.Comment", b =>
                {
                    b.HasOne("ProjectWebIV_Backend.Models.Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
